name: express-postgresql-app-cd

on:
  release:
    types:
      - released
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #- uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          printenv
          echo "/files1/${github.ref##*refs/tags\/}"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
