name: express-postgresql-app-ci

on:
  workflow_dispatch

defaults:
  run:
    working-directory: ./express-postgresql-app
    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.get_version_info.outputs.RELEASE_VERSION }}
      RELEASE_NAME: ${{ steps.get_version_info.outputs.RELEASE_NAME }}    
      RELEASE_FILE_NAME: ${{ steps.get_version_info.outputs.RELEASE_FILE_NAME }}    
    env:
      RELEASE_VERSION: "2.0.0"
      RELEASE_NAME: "express-postgresql-app.zip"
      RELEASE_FILE_NAME: "express-postgresql-app"
    steps:
      - uses: actions/checkout@v2
        
      #- name: Validate deployment template(s)
      #  run: az bicep build --file ./scripts/deployment-uat.bicep
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          
      - name: Restore all project dependencies
        run: npm install
      
      - name: Generate a unique package version
        id: get_version_info
        run: |
        
          declare releaseOrigVersion=""
          declare releaseVersion=""
          declare releaseName=""
          declare releaseFileName=""
          
          releaseOrigVersion=$(cat ./package.json | jq '.version')
          releaseOrigVersion="${releaseOrigVersion%\"}"
          releaseOrigVersion="${releaseOrigVersion#\"}"
          releaseVersion="${releaseOrigVersion}.${{github.run_number}}"
          
          cat ./package.json | jq ". |= . + { \"version\": \"${releaseVersion}\" }" > ./package.new.json
          mv ./package.json ./package.old.json
          mv ./package.new.json ./package.json
          rm ./package.old.json
          
          releaseName="express-postgresql-app-${releaseVersion}"
          releaseFileName="express-postgresql-app-${releaseVersion}.zip"
          
          echo "RELEASE_VERSION=$releaseVersion" >> $GITHUB_ENV
          echo "RELEASE_NAME=$releaseName" >> $GITHUB_ENV
          echo "RELEASE_FILE_NAME=$releaseFileName" >> $GITHUB_ENV

          echo "::set-output name=RELEASE_VERSION::$releaseVersion"
          echo "::set-output name=RELEASE_NAME::$releaseName"
          echo "::set-output name=RELEASE_FILE_NAME::$releaseFileName"
          
      - name: Build and validate
        run: npm run build
      
      - name: Run unit tests
        run: npm run test
      
      - name: Remove test artifacts
        run: |
          rm -rf node_modules
          npm install --production
        
      - name: Publish a package
        run: npm publish --tag {{$github.sha}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create an application archive
        run: |
         zip -q -m "../${{ env.PACKAGE_FILE_NAME }}" ./* .*
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_FILE_NAME }}
          tag_name: ${{ env.RELEASE_NAME }}
          files: ${{ env.RELEASE_FILE_NAME }}
          token: ${{ secrets.PAT_TOKEN }} # To trigger other workflows

      # No longer supported:
      #- name: Create Release
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: ${{ env.PACKAGE_VERSION }}
      #    release_name: ${{ env.PACKAGE_VERSION }}
      #    body: "Express-postgresql-app Version ${{ env.PACKAGE_VERSION }}"
      #    draft: false
      #    prerelease: true
          
      #- name: Upload Release Asset
      #  id: upload-release-asset
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
      #    filename: "./${{ env.PACKAGE_FILE_NAME }}"
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: "./${{ env.PACKAGE_FILE_NAME }}"
      #    asset_name: ${{ env.PACKAGE_FILE_NAME }}
      #    asset_content_type: application/zip
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download release
        run: |
          echo ${{needs.build.outputs.RELEASE_VERSION}}
          curl -sL -H "Accept:application/octet-stream" https://github.com/martinabrle/node-learning-path/releases/download/express-postgresql-app-2.0.26/express-postgresql-app-2.0.26.zip -o ./express-postgresql-app-2.0.26.zip
      
      #- name: Azure login
       # uses: azure/login@v1
       # with:
       #   client-id: ${{ secrets.AZURE_UAT_CLIENT_ID }}
       #   tenant-id: ${{ secrets.AZURE_UAT_TENANT_ID }}
       #   subscription-id: ${{ secrets.AZURE_UAT_SUBSCRIPTION_ID }}
