name: express-postgresql-app-release

on:
  release:
    types:
      - released
    branches:
      - main      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get release
        id: release
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
  
      - name: Download release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "martinabrle/node-learning-path"
          version: "tags/${{steps.release.outputs.VERSION}}"
          file: "${{steps.release.outputs.VERSION}}.zip"
          target: "${{steps.release.outputs.VERSION}}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Display version
        run: |
          echo "Add other actions to log in and deploy version ${{ steps.release.outputs.VERSION }}to PROD"
