name: Node.js Package

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./express-postgresql-app
    steps:
      - uses: actions/checkout@v2
      
      - name: Validate deployment template(s)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az bicep build --file ./scripts/deployment-uat.bicep
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          
      - name: Restore project dependencies
        run: npm install
      
      - name: Generate unique package version
        run: |
          origPackageVersion=$(cat ./package.json | jq '.version') |
          origPackageVersion="${origPackageVersion%\"}" |
          origPackageVersion="${origPackageVersion#\"}" |
          packageVersion="${origPackageVersion}.${{GITHUB_SHA}}" |
          cat ./package.json | jq ". |= . + { \"version\": \"${packageVersion}\" }">package.json |
          run: echo '::set-output packageVersion="$(packageVersion)"'
          
      - name: Build and validate
        run: npm run build
      
      - name: Run unit tests
        run: npm run test
      
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
